version: 2.1

jobs:
  notify:
    machine:
      image: ubuntu-2004:current
    steps:
      - checkout
      - run: ./.ci/integromat.sh

workflows:
  default:
    jobs:
      - notify
  daily:
    triggers:
      - schedule:
          # Every day, 0423Z.
          cron: "23 4 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - notify
